# Используем официальный образ Python
FROM python:3.9-slim

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем файл с зависимостями
COPY requirements.txt /app

# Устанавливаем зависимости
RUN pip install --no-cache-dir -r requirements.txt

# Копируем файлы приложения
COPY . /app

# Установка переменной окружения для подключения к MongoDB
ENV MONGO_URI=mongodb://webscraper-mongo:27017/python_db
# Запуск приложения
CMD ["python", "run.py"]
