version: '3.8'

services:
  engine:
    build:
      context: .
      dockerfile: Dockerfile.engine
    container_name: webscraper-engine-new
    environment:
      - MONGO_URI=mongodb+srv://Python1:VI9Mb3hDJoDn4nb4@python.0c7bytz.mongodb.net/python_db

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: webscraper-web-new
    environment:
      - MONGO_URI=mongodb+srv://Python1:VI9Mb3hDJoDn4nb4@python.0c7bytz.mongodb.net/python_db
    ports:
      - "5000:5000"
